---
title: ""
output: 
  html_document:
    includes:
       in_header: GA.html
---

## Invited Lectures and Talks

- Ministry of Development: "Kısa dönemli ekonomik büyüme tahmini - R ile Nowcasting" [In English: Short-term economic growth forecasting - Nowcasting with R], 12-21 April 2017.

- VakıfBank: "R istatistiksel programlama diline giriş" [In English: Introduction to R statistical programming language], 28-29 January 2016.
	
- Turkish Statistical Institute: "R ile paralel programalama ve büyük veri analizi" [In English: Parallel programming and big data analysis with R], 16-20 January 2016.
		
- Türkiye İş Bankası: "R istatistiksel programlama dili" [In English: R statistical programming language], 13-15 August 2014.



## Grants and Awards

- [12.2018 - 07.2021] TUBITAK - The Support Program for Scientific and Technological Research Projects (1001): "Türkiye'de asgari ücretlerin işgücü piyasasına etkileri, 2005-2018" [In English: The effects of minimum wages on the labor market in Turkey, 2005-2018] (with İ. Tunalı, S. Polat and B.İ. Yanık)
  
  
- [09.2019 - 02.2021] PMI IMPACT: "Analysis of the Illegal Trade of Alcoholic Beverages, Cigarettes and Tobacco, Fuel and Mobile Phones in Turkey" (with S. Gürsel and G.U. Kolaşin)

  
- [09.2013 - 03.2015] TUBITAK - The Support Program for Scientific and Technological Research Projects (1001): "Türkiye'de firma verimliliği: evrimi, dağılımı ve faktör dağılımındaki etkinsizliklerin rolü" [In: English: Firm productivity in Turkey: its evolution, distribution and role in misallocation of factors] (with I. Atiyas)

- [04.2013 - 12.2013] Ministry of Education & ERG & UNICEF: "Temel Belirleyicileri Açısından İlköğretimde Okula Devam ve Devamsızlık" [In English: Key Determinants of School Attendance and Absenteeism in Primary Education] (with B. Börkan, H. Levent, O. Dereli and S. Pelek)

- [09.2010 - 02.2011] TÜBİTAK - Postdoctoral Research Grant (2219).
- [09.2005 - 06.2006] Agence Universitaire de la Francophonie (AUF) - Training Through Research Fellowship.
- [10.2001 - 09.2002] EGIDE - Eiffel Graduate Scholarship.
- [10.2000 - 01.2001] Robert Schuman Foundation - Undergraduate Scholarship.



## Funded Research Projects
- [02.2024 - 11.2024]  GYODER: "İnşaat Sektörü ve İşgücü Dinamikleri: Türkiye’24" [In English: Construction Sector and Labor Dynamics: Turkiye ’24]  (with S. Gürsel)
- [09.2023 - 10.2023]  ZAY Strategy: "Türkiye'de Fındık Sektörünün Sorunları ve Geleceği"
 [In English: Challenges and Future Prospects of the Hazelnut Sector in Turkiye] (with S. Gürsel)

- [12.2021 - 05.2022]  TURKCELL: 
Türkiye’de Bilgi İletişim Harcamaları ve Dijitalleşme [In English: Information and Communications Technology Expenditure and Digitalization in Turkiye]  (with E. Köksal)

- [09.2020 - 03.2021] World Energy Council - Turkey & Istanbul Center for Regulation:  "Decarbonizing Turkey’s Energy Provision 2050" (with D. E. Dalgıç-Tetikol, P. Deniz, M. Finger, İ. Gümüş, and E. Köksal)



## Professional Activities

__Referee for:__ 

- Journal of Public Economics 
- Economics of Transition
- Applied Economics 
- Empirical Economics
- Central Bank Review
- İktisat İşletme ve Finans
- TCMB Çalışma Tebliği Serisi


__Postdoctoral research:__ Montreal University (2010, 8 months)


__Conference and Workshop Presentations:__ 


- 2023-2024:  Bahcesehir University - FEASS Research Seminar; 
Istanbul Bilgi University  - Economics Department Seminar; 
The 30th TEA Conference on Economics - Türkiye Ekonomi Kurumu;  Sagalassos Çalıştayı (ITU)

- 2022-2023: Galatasaray University - Friday Seminar;  Bogazici University - Economics Department Seminar;
 6th Annual Istanbul Meeting on Human Capital (BAU \& LSU \& GIAM)

- 2020-2021: 
 ERF 27th Annual Conference - Webinar Sessions;
 Bahcesehir University - FEASS Research Seminar;
 Gebze Technical University University - Economics Department Seminar

- 2019-2020: Sabanci University - Economics Seminar

- 2018-2019: Istanbul Technical University - Economics Department Seminar;
 4th Annual Istanbul Meeting on Human Capital (BAU \& LSU \& GIAM)

- 2016-2017: Özyeğin University-World Bank Workshop on “Poverty, Inequality and Intergenerational Mobility”

- 2015-2016: 1st Annual Istanbul Meeting on Human Capital (Koc Uni \& LSU)

- 2013-2014: 34th Annual Meeting of the MEEA; GDRI DREEM Conference on “Evaluation of Economic Policies and Institutional Changes in Mediterranean Countries”; 12th International Conference of the MEEA

- 2009-2010: 9th International Conference of the MEEA; GDRI DREEM Conference on “Inequalities and development in the Mediterranean countries”

- 2006-2007: 16th International Input-output Conference

- 2005-2006: 8th International Meeting of the Society for Social Choice and Welfare

- 2004-2005: Workshop of FEMISE Research Group FEM21-39 (FEMISE III), 23-26 June 2005, Rabat, Morocco.

- 2003-2004: METU Conference in Economics

