---
title: ""
output: 
  html_document:
    includes:
       in_header: GA.html
---


## Codes for published and working papers

Code for "Transitional Dynamics and the Optimal Progressivity of Income Redistribution" [Download from the IDEAS website](https://ideas.repec.org/c/red/ccodes/13-232.html)

Data for "Türkiye ekonomisinde toplam faktör verimliliğinin seyri: sektörel bakış, 1980-2018" [Download from Betam's website](https://betam.bahcesehir.edu.tr/wp-content/uploads/2020/07/EK_Seriler.rar)



## R Packages

```{r, echo=FALSE, results='asis'}
library(yaml)
if (file.exists("_projects/rbrsa.yml")) {
  proj <- yaml::read_yaml("_projects/rbrsa.yml")
  cat('###', proj$title, '\n\n')
  cat(proj$description, '\n\n')
  cat('[', proj$link_text, '](', proj$link_url, '){target="_blank"}\n')
  cat('[GitHub Repo](', proj$github, '){target="_blank"}\n')
  cat('\n---\n')
}
```

## Python Packages

```{r, echo=FALSE, results='asis'}
library(yaml)
if (file.exists("_projects/pybrsa.yml")) {
  proj <- yaml::read_yaml("_projects/pybrsa.yml")
  cat('###', proj$title, '\n\n')
  cat(proj$description, '\n\n')
  cat('[', proj$link_text, '](', proj$link_url, '){target="_blank"}\n')
  cat('[GitHub Repo](', proj$github, '){target="_blank"}\n')
  cat('\n---\n')
} else {
  cat('_No Python packages listed yet._\n')
}
```