---
title: ""
output: 
  html_document:
    includes:
       in_header: GA.html
---


## R tutorials


Here are some PDF slides I used for R presentations.

- [Introduction to R ](R_tut/R_intro.pdf)
- [Multiple regression with R ](R_tut/R_ols.pdf)
- [Regression with pooled cross sections](R_tut/R_pooled.pdf)
- [Regression with panel data](R_tut/R_panel.pdf)
- [Seasonal adjustment and forecasting](R_tut/R_ts.pdf)
- [Data manipulation with dplyr/tidyverse](R_tut/R_reshape.pdf)
- [R graphics](R_tut/R_graphs.pdf)


Please see also the list of documents that are freely available on the R website:  

https://www.r-project.org/other-docs.html




## Graduate classes

- Econometrics I, Bahcesehir University, 2022-2023.
- Macroeconomic Theory, Bahcesehir University, 2017-2018.
- Macroeconomics I, Galatasaray University, 2011-2014.
- Macroeconomics II, Galatasaray University, 2010-2014.

## Undergraduate classes

- Data Science with R, Bahcesehir University, 2022-2024
- Machine Learning with R, Bahcesehir University, 2023-2025
- Econometrics I, Bahcesehir University, 2017-2021.
- Econometrics II, University of Montreal, 2011; Bahcesehir University, 2017-2021.
- Public Finance, Sabanci University, 2016; Bahcesehir University, 2017-2018.
- Macroeconomics, Galatasaray University, 2009, 2010.
- Programming in Economics, Galatasaray University, 2009, 2010.
- Microeconomics, Galatasaray University, 2009.

